apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjobmonitor-deployment
  labels:
    app.kubernetes.io/name: cronjobmonitor-deploymen
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cronjobmonitor-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cronjobmonitor-deployment
    spec:
      containers:
        - name: monitor-bad-cronjob
          image: helloworld-webserver:1.0
          imagePullPolicy: IfNotPresent
          command:
          - bash
          - -c
          - |
            while true; do
              echo -n "." 
              sleep 10
            done
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 1
            exec:
              command:
              - bash
              - -c
              - /scripts/getcronjobinvocationstatus.sh bad-cronjob
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        - name: monitor-good-cronjob
          image: helloworld-webserver:1.0
          imagePullPolicy: IfNotPresent
          command:
          - bash
          - -c
          - |
            while true; do
              echo -n "." 
              sleep 10
            done
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 1
            exec:
              command:
              - bash
              - -c
              - /scripts/getcronjobinvocationstatus.sh good-cronjob
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
