apiVersion: batch/v1
kind: CronJob
metadata:
  name: good-cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: helloworld-webserver:1.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from Kubernetes!
          restartPolicy: Never
      backoffLimit: 0  
      parallelism: 1
      completions: 1